# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-workflow-state',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-workflow-state',
                'lib_path': 'cjm_workflow_state'},
  'syms': {}}
