"""Generic undo history stack for workflow operations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/history.ipynb.

# %% auto #0
__all__ = ['DEFAULT_MAX_HISTORY_DEPTH', 'push_history', 'pop_history']

# %% ../nbs/history.ipynb #hist-imports
from typing import Optional, Tuple, List, Dict, Any

# %% ../nbs/history.ipynb #hist-const
DEFAULT_MAX_HISTORY_DEPTH = 50

# %% ../nbs/history.ipynb #hist-push
def push_history(
    history: List[Dict[str, Any]],  # Current history stack
    snapshot: Dict[str, Any],  # State snapshot to save
    max_depth: int = DEFAULT_MAX_HISTORY_DEPTH,  # Maximum history depth
) -> List[Dict[str, Any]]:  # Updated history stack
    """Push a state snapshot onto the history stack, enforcing max depth."""
    new_history = list(history)
    new_history.append(snapshot)
    if len(new_history) > max_depth:
        new_history = new_history[-max_depth:]
    return new_history

# %% ../nbs/history.ipynb #hist-pop
def pop_history(
    history: List[Dict[str, Any]],  # Current history stack
) -> Optional[Tuple[Dict[str, Any], List[Dict[str, Any]]]]:  # (snapshot, updated_history) or None
    """Pop the most recent snapshot from the history stack."""
    if not history:
        return None
    new_history = list(history)
    snapshot = new_history.pop()
    return snapshot, new_history
