"""SQLite-backed workflow state storage for persistence across restarts."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/state_store.ipynb.

# %% auto #0
__all__ = ['SQLiteWorkflowStateStore']

# %% ../nbs/state_store.ipynb #ss-imports
import json
import sqlite3
from pathlib import Path
from typing import Dict, Any, Optional
from contextlib import contextmanager

# %% ../nbs/state_store.ipynb #ss-class
class SQLiteWorkflowStateStore:
    """SQLite-backed workflow state storage for persistence across restarts."""
    
    def __init__(
        self,
        db_path: Path  # Path to SQLite database file
    ):
        """Initialize the state store and create tables if needed."""
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()
    
    @contextmanager
    def _get_connection(self):  # Context manager yielding SQLite connection
        """Get a database connection with proper cleanup."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        finally:
            conn.close()
    
    def _init_db(self) -> None:
        """Initialize database schema."""
        with self._get_connection() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS workflow_state (
                    flow_session_key TEXT PRIMARY KEY,
                    current_step TEXT,
                    state_json TEXT DEFAULT '{}',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_workflow_state_updated
                ON workflow_state(updated_at)
            """)
    
    def _make_key(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str  # Session identifier string
    ) -> str:  # Composite key for storage
        """Create composite key from flow_id and session_id."""
        return f"{flow_id}:{session_id}"
    
    def get_current_step(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str  # Session identifier string
    ) -> Optional[str]:  # Current step ID or None
        """Get current step ID for a workflow."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            row = conn.execute(
                "SELECT current_step FROM workflow_state WHERE flow_session_key = ?",
                (key,)
            ).fetchone()
            return row["current_step"] if row else None
    
    def set_current_step(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str,  # Session identifier string
        step_id: str  # Step ID to set as current
    ) -> None:
        """Set current step ID for a workflow."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            conn.execute("""
                INSERT INTO workflow_state (flow_session_key, current_step)
                VALUES (?, ?)
                ON CONFLICT(flow_session_key) DO UPDATE SET
                    current_step = excluded.current_step,
                    updated_at = CURRENT_TIMESTAMP
            """, (key, step_id))
    
    def get_state(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str  # Session identifier string
    ) -> Dict[str, Any]:  # Workflow state dictionary
        """Get all workflow state."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            row = conn.execute(
                "SELECT state_json FROM workflow_state WHERE flow_session_key = ?",
                (key,)
            ).fetchone()
            if row and row["state_json"]:
                return json.loads(row["state_json"])
            return {}
    
    def update_state(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str,  # Session identifier string
        updates: Dict[str, Any]  # State updates to merge
    ) -> None:
        """Update workflow state by merging new values."""
        key = self._make_key(flow_id, session_id)
        current_state = self.get_state(flow_id, session_id)
        current_state.update(updates)
        state_json = json.dumps(current_state)
        with self._get_connection() as conn:
            conn.execute("""
                INSERT INTO workflow_state (flow_session_key, state_json)
                VALUES (?, ?)
                ON CONFLICT(flow_session_key) DO UPDATE SET
                    state_json = excluded.state_json,
                    updated_at = CURRENT_TIMESTAMP
            """, (key, state_json))
    
    def clear_state(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str  # Session identifier string
    ) -> None:
        """Clear all workflow state."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            conn.execute(
                "DELETE FROM workflow_state WHERE flow_session_key = ?",
                (key,)
            )
    
    def get_step_state(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str,  # Session identifier string
        step_id: str  # Step identifier
    ) -> Dict[str, Any]:  # Step-specific state dictionary
        """Get state for a specific step."""
        state = self.get_state(flow_id, session_id)
        step_key = f"_step_{step_id}"
        return state.get(step_key, {})
    
    def update_step_state(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str,  # Session identifier string
        step_id: str,  # Step identifier
        updates: Dict[str, Any]  # Step-specific state updates
    ) -> None:
        """Update state for a specific step."""
        step_key = f"_step_{step_id}"
        current_step_state = self.get_step_state(flow_id, session_id, step_id)
        current_step_state.update(updates)
        self.update_state(flow_id, session_id, {step_key: current_step_state})
    
    def clear_step_state(
        self,
        flow_id: str,  # Workflow identifier
        session_id: str,  # Session identifier string
        step_id: str  # Step identifier
    ) -> None:
        """Clear state for a specific step."""
        step_key = f"_step_{step_id}"
        state = self.get_state(flow_id, session_id)
        if step_key in state:
            del state[step_key]
            key = self._make_key(flow_id, session_id)
            state_json = json.dumps(state)
            with self._get_connection() as conn:
                conn.execute("""
                    UPDATE workflow_state SET state_json = ?, updated_at = CURRENT_TIMESTAMP
                    WHERE flow_session_key = ?
                """, (state_json, key))
