"""SQLite-backed workflow state storage for persistence across restarts."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/state_store.ipynb.

# %% auto #0
__all__ = ['SessionSummary', 'SQLiteWorkflowStateStore']

# %% ../nbs/state_store.ipynb #ss-imports
import json
import sqlite3
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Any, Optional, List
from contextlib import contextmanager

# %% ../nbs/state_store.ipynb #f5c93b25
@dataclass
class SessionSummary:
    """Lightweight metadata for a single workflow session."""
    flow_id:str # Workflow identifier
    session_id:str # Session identifier
    label:Optional[str] # Human-readable label, or None to defer to a generator
    current_step:Optional[str] # Current StepFlow step ID, or None
    created_at:str # ISO timestamp string from SQLite CURRENT_TIMESTAMP
    updated_at:str # ISO timestamp string from SQLite CURRENT_TIMESTAMP
    state_size_bytes:int # Length of state_json column — cheap size hint

# %% ../nbs/state_store.ipynb #ss-class
class SQLiteWorkflowStateStore:
    """SQLite-backed workflow state storage for persistence across restarts."""
    
    def __init__(
        self,
        db_path:Path # Path to SQLite database file
    ):
        """Initialize the state store and create or migrate the schema."""
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()
    
    @contextmanager
    def _get_connection(self): # Context manager yielding a SQLite connection
        """Get a database connection with commit-on-success and guaranteed close."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        finally:
            conn.close()
    
    def _init_db(
        self,
    ) -> None:
        """Initialize the schema and run idempotent migrations."""
        with self._get_connection() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS workflow_state (
                    flow_session_key TEXT PRIMARY KEY,
                    current_step TEXT,
                    state_json TEXT DEFAULT '{}',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_workflow_state_updated
                ON workflow_state(updated_at)
            """)
            # Idempotent migration: add label column if missing.
            cursor = conn.execute("PRAGMA table_info(workflow_state)")
            columns = {row[1] for row in cursor.fetchall()}
            if "label" not in columns:
                conn.execute("ALTER TABLE workflow_state ADD COLUMN label TEXT")
    
    def _make_key(
        self,
        flow_id:str, # Workflow identifier
        session_id:str # Session identifier string
    ) -> str: # Composite "flow_id:session_id" key for storage
        """Build the composite primary key from flow and session IDs."""
        return f"{flow_id}:{session_id}"
    
    def get_current_step(
        self,
        flow_id:str, # Workflow identifier
        session_id:str # Session identifier string
    ) -> Optional[str]: # Current step ID, or None if no row exists
        """Get the current step ID for a session."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            row = conn.execute(
                "SELECT current_step FROM workflow_state WHERE flow_session_key = ?",
                (key,)
            ).fetchone()
            return row["current_step"] if row else None
    
    def set_current_step(
        self,
        flow_id:str, # Workflow identifier
        session_id:str, # Session identifier string
        step_id:str # Step ID to set as current
    ) -> None:
        """Set the current step ID for a session, upserting the row if needed."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            conn.execute("""
                INSERT INTO workflow_state (flow_session_key, current_step)
                VALUES (?, ?)
                ON CONFLICT(flow_session_key) DO UPDATE SET
                    current_step = excluded.current_step,
                    updated_at = CURRENT_TIMESTAMP
            """, (key, step_id))
    
    def get_state(
        self,
        flow_id:str, # Workflow identifier
        session_id:str # Session identifier string
    ) -> Dict[str, Any]: # Full session state dictionary
        """Get the full state dictionary for a session."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            row = conn.execute(
                "SELECT state_json FROM workflow_state WHERE flow_session_key = ?",
                (key,)
            ).fetchone()
            if row and row["state_json"]:
                return json.loads(row["state_json"])
            return {}
    
    def update_state(
        self,
        flow_id:str, # Workflow identifier
        session_id:str, # Session identifier string
        updates:Dict[str, Any] # Top-level state keys to merge in
    ) -> None:
        """Merge updates into the session state, upserting the row if needed."""
        key = self._make_key(flow_id, session_id)
        current_state = self.get_state(flow_id, session_id)
        current_state.update(updates)
        state_json = json.dumps(current_state)
        with self._get_connection() as conn:
            conn.execute("""
                INSERT INTO workflow_state (flow_session_key, state_json)
                VALUES (?, ?)
                ON CONFLICT(flow_session_key) DO UPDATE SET
                    state_json = excluded.state_json,
                    updated_at = CURRENT_TIMESTAMP
            """, (key, state_json))
    
    def clear_state(
        self,
        flow_id:str, # Workflow identifier
        session_id:str # Session identifier string
    ) -> None:
        """Delete the session row entirely. Idempotent."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            conn.execute(
                "DELETE FROM workflow_state WHERE flow_session_key = ?",
                (key,)
            )
    
    def get_step_state(
        self,
        flow_id:str, # Workflow identifier
        session_id:str, # Session identifier string
        step_id:str # Step identifier
    ) -> Dict[str, Any]: # State dictionary for that step
        """Get the state dictionary for a specific step."""
        state = self.get_state(flow_id, session_id)
        step_key = f"_step_{step_id}"
        return state.get(step_key, {})
    
    def update_step_state(
        self,
        flow_id:str, # Workflow identifier
        session_id:str, # Session identifier string
        step_id:str, # Step identifier
        updates:Dict[str, Any] # Step state keys to merge in
    ) -> None:
        """Merge updates into a specific step's state."""
        step_key = f"_step_{step_id}"
        current_step_state = self.get_step_state(flow_id, session_id, step_id)
        current_step_state.update(updates)
        self.update_state(flow_id, session_id, {step_key: current_step_state})
    
    def clear_step_state(
        self,
        flow_id:str, # Workflow identifier
        session_id:str, # Session identifier string
        step_id:str # Step identifier
    ) -> None:
        """Remove a specific step's state while preserving the rest of the session."""
        step_key = f"_step_{step_id}"
        state = self.get_state(flow_id, session_id)
        if step_key in state:
            del state[step_key]
            key = self._make_key(flow_id, session_id)
            state_json = json.dumps(state)
            with self._get_connection() as conn:
                conn.execute("""
                    UPDATE workflow_state SET state_json = ?, updated_at = CURRENT_TIMESTAMP
                    WHERE flow_session_key = ?
                """, (state_json, key))
    
    def create_session(
        self,
        flow_id:str, # Workflow identifier
        session_id:Optional[str]=None, # Pre-chosen session ID (auto-generated UUID4 if None)
        label:Optional[str]=None # Optional human-readable label
    ) -> str: # The created session_id
        """Insert a new empty session row and return its session_id."""
        if session_id is None:
            session_id = str(uuid.uuid4())
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            conn.execute(
                "INSERT INTO workflow_state (flow_session_key, label) VALUES (?, ?)",
                (key, label)
            )
        return session_id
    
    def session_exists(
        self,
        flow_id:str, # Workflow identifier
        session_id:str # Session identifier string
    ) -> bool: # True if a row exists for the given session
        """Check whether a session row exists."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            row = conn.execute(
                "SELECT 1 FROM workflow_state WHERE flow_session_key = ?",
                (key,)
            ).fetchone()
            return row is not None
    
    def get_session_summary(
        self,
        flow_id:str, # Workflow identifier
        session_id:str # Session identifier string
    ) -> Optional[SessionSummary]: # Session metadata, or None if not found
        """Return lightweight metadata for a single session."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            row = conn.execute("""
                SELECT current_step, label, created_at, updated_at, length(state_json) AS size
                FROM workflow_state WHERE flow_session_key = ?
            """, (key,)).fetchone()
        if row is None:
            return None
        return SessionSummary(
            flow_id=flow_id,
            session_id=session_id,
            label=row["label"],
            current_step=row["current_step"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            state_size_bytes=row["size"] or 0,
        )
    
    def list_sessions(
        self,
        flow_id:str, # Workflow identifier to list sessions for
        order_by:str="updated_at", # Sort column: "updated_at", "created_at", or "label"
        descending:bool=True # Sort direction
    ) -> List[SessionSummary]: # All sessions for this flow, ordered
        """List all sessions for a flow as lightweight SessionSummary records."""
        if order_by not in ("updated_at", "created_at", "label"):
            raise ValueError(f"Invalid order_by: {order_by!r}")
        direction = "DESC" if descending else "ASC"
        prefix = f"{flow_id}:"
        with self._get_connection() as conn:
            rows = conn.execute(f"""
                SELECT flow_session_key, current_step, label, created_at, updated_at,
                       length(state_json) AS size
                FROM workflow_state
                WHERE flow_session_key LIKE ?
                ORDER BY {order_by} {direction}
            """, (f"{prefix}%",)).fetchall()
        return [
            SessionSummary(
                flow_id=flow_id,
                session_id=r["flow_session_key"][len(prefix):],
                label=r["label"],
                current_step=r["current_step"],
                created_at=r["created_at"],
                updated_at=r["updated_at"],
                state_size_bytes=r["size"] or 0,
            )
            for r in rows
        ]
    
    def set_session_label(
        self,
        flow_id:str, # Workflow identifier
        session_id:str, # Session identifier string
        label:Optional[str] # New label, or None to clear
    ) -> None:
        """Update the session label. No-op if the session does not exist."""
        key = self._make_key(flow_id, session_id)
        with self._get_connection() as conn:
            conn.execute("""
                UPDATE workflow_state
                SET label = ?, updated_at = CURRENT_TIMESTAMP
                WHERE flow_session_key = ?
            """, (label, key))
    
    def delete_session(
        self,
        flow_id:str, # Workflow identifier
        session_id:str # Session identifier string
    ) -> None:
        """Delete a session row. Alias of `clear_state` for symmetry with the session API."""
        self.clear_state(flow_id, session_id)
